CREATE TABLE PackingDetail (
    PackingDetailID INT AUTO_INCREMENT PRIMARY KEY,
    PackingID INT NOT NULL,
    SKUItemID INT NOT NULL,
    PackedQuantity INT NOT NULL,

    FOREIGN KEY (PackingID) REFERENCES Packing(PackingID) ON DELETE CASCADE,
    FOREIGN KEY (SKUItemID) REFERENCES SKUItem(ItemID) ON DELETE CASCADE
);