--  SELECT 
--     p.*,
--     eh.OrderNumber AS OrderNumber,
--     el.LotNumber AS LotNumber,
--     w.Name AS WarehouseName, 
--     l.LocationName AS PackToLocationName,
--     u1.FullName AS CreatedByName,
--     u2.FullName AS UpdatedByName,
--     u3.FullName AS PackedByName,
--     pd.PackingDetailID,
--     pd.SKUItemID,
--     s.SKU,
--     pr.Name AS ProductName,
--     pd.PackedQuantity
-- FROM Packing p
-- LEFT JOIN ExportOrderHeader eh ON p.OrderID = eh.OrderID
-- LEFT JOIN ExportOrderLineItem el ON p.OrderLineItemID = el.OrderLineItemID
-- LEFT JOIN Warehouse w ON p.WarehouseID = w.WarehouseID
-- LEFT JOIN Location l ON p.PackToLocationID = l.LocationID
-- LEFT JOIN User u1 ON p.CreatedBy = u1.UserID
-- LEFT JOIN User u2 ON p.UpdatedBy = u2.UserID
-- LEFT JOIN User u3 ON p.PackedBy = u3.UserID
-- LEFT JOIN PackingDetail pd ON p.PackingID = pd.PackingID
-- LEFT JOIN SKUItem s ON pd.SKUItemID = s.ItemID
-- LEFT JOIN Product pr ON s.ProductID = pr.ProductID
-- WHERE p.OrderLineItemID = 64
-- ORDER BY p.PackingID