CREATE TABLE ShipmentPacking (
    ShipmentPackingID INT AUTO_INCREMENT PRIMARY KEY,
    ShipmentID INT NOT NULL,
    PackingID INT NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (ShipmentID) REFERENCES Shipment(ShipmentID) ON DELETE CASCADE,
    FOREIGN KEY (PackingID) REFERENCES Packing(PackingID) ON DELETE CASCADE
);